feat: add setQueryData、getQueryData
EchoTechFE/taube pull request #2
Opened 2024-08-09 07:53 UTC by Britt-Xie

2024-08-09 08:10 UTC, zhuscat requested changes

2024-08-09 08:10 UTC, zhuscat commented on src/index.ts
> +    const keyRef = useKeyRef(queryKey)
这里不用使用 useKeyRef，本身 `setQueryData` 就不需要响应式的

2024-08-09 08:10 UTC, zhuscat commented on src/index.ts
> +      const newData =
没找到为什么需要创建 observer 呢？

2024-08-09 08:10 UTC, zhuscat commented on src/index.ts
> +      const observer: any = m.get(kHash)
不要 any

2024-08-09 08:10 UTC, zhuscat commented on src/index.ts
> +            ? (updater as (oldData: T | undefined) => T)(currentData)
这里 ts 不会自动推断吗？不用 `as`?

2024-08-09 08:10 UTC, zhuscat commented on src/index.ts
> +        scheduleTimeout(
这里需要 scheduleTimeout？

2024-08-09 08:10 UTC, zhuscat commented on src/index.ts
> +    const keyRef = useKeyRef(queryKey)
同样这里不需要响应式

2024-08-09 08:12 UTC, Britt-Xie commented on src/index.ts
> +      const newData =
> 没找到为什么需要创建 observer 呢？

官方的使用说法是如果传入的 queryKey 不存在就会创建一个新的查询，我跑了 demo， 确实通过 getQueryData 可以获取到那个不存在的 queryKey 的数据
![image](https://github.com/user-attachments/assets/fc9140ec-2e5e-48a3-936f-b9e5aaedf164)

2024-08-09 08:17 UTC, Britt-Xie commented on src/index.ts
> +        scheduleTimeout(
> 这里需要 scheduleTimeout？

我看官方提到了这个
![image](https://github.com/user-attachments/assets/2627a5d0-58c6-4aea-ba29-fe0533d21a4f)

2024-08-14 06:08 UTC, zhuscat requested changes

2024-08-14 06:08 UTC, zhuscat commented on src/index.ts
> +            ? (updater as (data: typeof currentData) => typeof currentData)(
这里不是自动推导的吗？为啥还要自己写类型啊，上面已经定义了 `T | ((oldData: T | undefined) => T)`？

2024-08-15 03:30 UTC, merged